### ISSUE TITLE
Issue with Dice Tray and Token Health

### ISSUE THREAD

**Issue by Seanny101** [schlosrat/token-health#32]
I am having an issue with Token Health when I select or target a token.
Then I use dice tray to make a roll, which happens with Dice So Nice and a chat message-all good.
Then if I press 'enter 'nothing happens.
I need to click randomly on screen (don't have to select token by the way) ,then 'enter' correctly opens Token Health dialogue.

If I don't use Dice Tray then Token Health works all OK.

It is strange .

Like your module a lot ,it is very handy when I use a macro to make a custom to hit roll attack and then I want to apply damage. This is the reason I have been using Dice Tray,to generate my hit point damage. Then I go to apply it by straight away clicking 'enter' and your Token Health dialogue will not come up unless i click on screen first (even pushing keys other than enter will not clear the bug-must left mouse click on screen).

**Comment by schlosrat** [comment]
Thanks Seanny101. I've never used Dice Tray so I've not seen this issue. I'll download that module and see if I can sort out what's going on. If I'm able to sort it out and fix the issue I'll post here and release a new version with the fix.

One thought might be to use a different key to trigger Token Health. That might be a workaround if Enter is getting trapped somehow by Dice Tray.

**Comment by Seanny101** [comment]
Cool thanks - Token Health is very nice to use.
I have modified my 'to hit" macro to include a clickable dice roll, this means I don't have to use dice tray, this has stopped issue for me at least for the present.
Probably should add I have been using OSE Ruleset in case this is important.

**Comment by schlosrat** [comment]
Hey Seanny101 I've updated Token Health to use DF Hotkeys in place of the old key binding system. This was done to enable things to work correctly in 0.8.x. It may or may not make a difference with Dice Tray, but since the problem you reported had to do with key bindings this might help you. Also, it makes it pretty easy to switch things around and use something else other than the Enter key.

I'll close this issue now, but please do try the new version and let me know if that works for you. The new version will require that you also have Library: DF Hotkeys installed, so please be sure you've got that module as well.

Cheers!
