### ISSUE TITLE
Option to have both Harm and Heal buttons

### ISSUE THREAD

**Issue by apoapostolov** [schlosrat/token-health#35]
Instead just one button that changes color when using special shortcuts, an option to display two buttons red and green (red on top of green as default) that apply logic rather than require negative values.

**Comment by schlosrat** [comment]
Thanks for the suggestion! I do want Token Health to be as easy and intuitive to use as possible.

As you've observed there are already two ways to deal with healing vs damage - either the hot keys used to launch the dialog or entering either positive or negative numbers as the case needs to be for the desired effect. Given that, I'm going to hold off for now on changing the UI in favor of what I see as a more pressing need.

The more pressing need at this time is to cope with game systems in which damage is recorded as a positive value increasing from perfectly healthy (0) up to some death threshold, and healing is conversely negative. This is a more complex change than it sounds and will enable the use of Token Health in such games. I think it's more important to make sure Token Health works for a wider set of games since there are already multiple ways to switch from damage to healing.

Thanks!
