### ISSUE TITLE
In 0.8.4 TokenHealth prevents DEL button from deleting lights, actors, templates

### ISSUE THREAD

**Issue by apoapostolov** [schlosrat/token-health#38]
It seems the mod prevents the DEL button to be read by the system, leading to inability to delete objects.

**Comment by rmasoni** [comment]
This is related to its keyboard shortcuts being reset every refresh to `[object Object]`. When you set the shortcuts, other keys go back to normal, but again, it resets after a refresh.

This is still broken on 0.8.5.

**Comment by apoapostolov** [comment]
So I should wait for 0.8.6? Are you aware if Atro is fixing this for the next RC?

**Comment by schlosrat** [comment]
Fixed in Token Health v 0.4.0

Basically, the old keybinding method Token Health was using is broken in FVTT 0.8.x. In this new version of Token Health the main thing that's different is that now it's using DF HotKeys for the key bindings. Things seem to work on my end (tested in dnd5e only so far). There are other things that no doubt need testing, but this may at least get you running.

Please follow up with new issues if you find anything else.
