### ISSUE TITLE
Request: Support for Star Wars/Genesys

### ISSUE THREAD

**Issue by Chromie192** [schlosrat/token-health#52]
For this system you add up your damage rather than subtracting from your health. Not sure if it's possible but I signed up just to request this, if feasible. I have no idea on what it would take.

**Comment by schlosrat** [comment]
This is already a capability for token health. Under Module Setting the second entry is a checkbox for Additive Damage with the note to "Enable this for systems where damage accumulates rather than subtracting from current health". Making Token Health compatible with SW may be as simple as checking this box.

That said, we can explore what settings are appropriate for SW and configure defaults for that system. Currently, this module recognizes and configures defaults for dnd5e, pf1, pf2e, swade, l5r5e, torgeternity, and age-system where swade, l5r5e, and torgeternity add default to using additive damage.

If you would like to tell me what settings you'd like for SW I can configure defaults for that as well.
