### ISSUE TITLE
Does this work with the automatic process of midi-qol at all? is it possible for it to?

### ISSUE THREAD

**Issue by Orionox** [schlosrat/token-health#56]
So I'd love if this module could work with midi-qols auto rolling/applying damage feature. How I imagine it working is whenever midi-qol calls for an attack roll the dialog that lets you select health/damage type is brought up which allows you to select the options you want and then midi-takes over and automates the rolls and application of damage.

**Comment by schlosrat** [comment]
Sorry for the slow reply, I'm just getting around to some 0.9 updates and saw this issue now as I've been swamped with other (life) things recently.

I've never used midi-qol so I really have no idea how much work would be involved in integrating these modules. As you've framed the problem it sounds as if at least some if not most of the effort would be on the midi-qol side since the behavior you're asking for seems to be a use case where you're using midi-qol to call token health. I'm not the maintainer for that mod, so you may need to start by reaching out to that person. If they're willing to make a change where their mod calls mine and they need me to do something on this end to enable or facilitate that then we might be able to make progress - otherwise not.

Please ask the midi-qol maintainer if they think this may be possible and have them reach out to me if they need changes on this end.
