### ISSUE TITLE
Damage chat message and healing chat messages don't use the same max HP limits (PF2e?)

### ISSUE THREAD

**Issue by itamarcu** [schlosrat/token-health#61]
Reproduction (in PF2e system, Token Health v0.5.1):
1. Have a token with e.g. 53/53 hp
2. Press enter, type "999", press enter to submit
3. The following is shown in the chat:

![image](https://user-images.githubusercontent.com/6516621/147745913-b0c8e48e-b83b-4599-8a2e-4605a9543e36.png)

Notice:
- Applying a lot of damage made it say "999 points of damage (wound)" - not limited by max hp (53)
- Applying a lot of healing made it say "53 points of healing (wound)" - limited by max hp

I think we want either both of them to say 999 or both of them to say 53.

**Comment by schlosrat** [comment]
Thanks, itamarcu. I'm working on the chat features right now. How about in instances like this is where either the damage or healing is greater than the amount the token can take it says something like X points of (wound/stun/etc) damage/healing (Y effective)? That way you'll get to see both how much you did and how much of that they took?

**Comment by itamarcu** [comment]
Sure, it could also be phrased...
> 999 points of wound damage (capped at 53)
> Dealt 999 wound damage (overkill after 53!)
> 53 wound damage (946 more than necessary!)

**Comment by schlosrat** [comment]
Fixed in 0.5.2. Please give this version a spin and see if it's working correctly for you now.

Note, this fix is folded in with the update to allow token chat codes for $D (total damage/healing applied), $DS (damage subtype), and $NE (net effect - damage or healing after any mitigation and limited by the token's ability to absorb the damage/healing)
