### ISSUE TITLE
Restrict Players stuck as checked despite saving.

### ISSUE THREAD

**Issue by Tobyn52** [schlosrat/token-health#67]
Honestly not sure if this is a problem on my end with module compatibility or what, but the Restrict Player Use remains checked despite me unchecking it and saving changes.  No errors are popping up in the JS console.

**Comment by schlosrat** [comment]
@Tobyn52
Which version of FVTT are you running? I've been testing with the latest stable build (V9 Build 242), and I've not been able to reproduce this problem.

I recommend you create a test world with the game system you're using and just Token Health - no other modules. Please see if this problem persists under those conditions. It may be as you've suggested a conflict with some other module, and this test will help us sort that out.

If the problem persists even without any other modules enabled, then please reply back here with the FVTT version your using and the game system (and its version) that you're using so that I can attempt to replicate the issue at my end.

If the problem resolves itself by running a clean world with no other modules, then you should begin adding the modules you like to run with one at a time. Between each module change, you'll need to see if the problem has shown up again. If it pops back up, then you've most likely just enabled the module that's having some sort of conflict with TH. I would need that information as well to try to replicate the problem. No guarantee I'll be able to fix the issue though if it turns out it's a problem on the other module's side - if it's bad behavior on the part of TH I should be able to get that sorted out.

**Comment by Tobyn52** [comment]
Following your advice, I've figured out the conflict was being caused by the Smart Doors module.  This can be marked solved.  Unchecking this in my home game immediately fixed the problem.

**Comment by schlosrat** [comment]
Thanks for following up!
