### ISSUE TITLE
[V10] Module does not work and prevents "Configure Settings" window from opening

### ISSUE THREAD

**Issue by r-valyar** [schlosrat/token-health#74]
For v10, when the module is enabled it does not work and it prevents the main "Configure Settings" dialog window from opening.

**Comment by schlosrat** [comment]
Actually, it's not Token Health that's causing the problem here. All of the Token Health functionality seems to work fine in V10 in terms of interacting with tokens and key bindings, etc.

This issue is that Token Health relies on Settings Extender, which is what's breaking your ability to open the core games Configure Settings menu. The same thing happens with Ping or other modules that also use Settings Extender. You can verify this by disabling Token Health and keeping Settings Extender. There is already an issue on that module's gitlab page (https://gitlab.com/foundry-azzurite/settings-extender/-/issues/10).

**Comment by schlosrat** [comment]
The issue was actually with Settings Extender, an obsolete dependency I should have removed long ago.

The dependency is gone in 0.5.6. Please try that version, and make sure you disable Settings Extender - that's the culprit for preventing the core game Configure Settings functionality from working.
